version: '3.8'

services:
  # Laravel Backend
  laravel:
    build:
      context: ./backend
    container_name: ecommerce_laravel
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    environment:
      - DB_CONNECTION=mongodb
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_DATABASE=ecommerce
    depends_on:
      - mongodb
    networks:
      - ecommerce

  # Vue.js Frontend
  vue:
    build:
      context: ./frontend
    container_name: ecommerce_vue
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - ecommerce

  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: ecommerce_mongodb
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce

volumes:
  mongodb_data:

networks:
  ecommerce:
    driver: bridge